version: '2'
services:
    api:
        build:
            context: ./api
        ports:
            - "5000:8080"
    web:
        build:
            context: ./web
        ports:
            - "3000:3000"
